
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *
from tkinter import ttk


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Python Programming\GUI-PRACTICES\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("665x640")
window.configure(bg = "#FFFFFF")

style = ttk.Style()
style.theme_use('default')

# Change the tab background color
bold_font = ("Helvetica", 10, "bold")
style.configure("TNotebook", background="#FFFFFF", borderwidth=0)
style.configure("TNotebook.Tab",
                background="#FFFFFF",
                foreground="#000000",
                padding=10,
                font=bold_font)

# Remove focus highlight (the dashed box)
style.layout("TNotebook.Tab",
            [('Notebook.tab', {'sticky': 'nswe', 'children':
                [('Notebook.padding', {'side': 'top', 'sticky': 'nswe', 'children':
                    [('Notebook.label', {'side': 'top', 'sticky': ''})],
                })],
            })])

# Optional: active tab background
style.map("TNotebook.Tab",
        background=[("selected", "#0E3269")],
        foreground=[("selected", "#FFFFFF")])

notebook = ttk.Notebook(window, style='TNotebook')
tab1 = Frame(notebook,bg="#0E3269", width=600, height=500)
tab2 = Frame(notebook)

notebook.add(tab1, text="Account tab")
notebook.add(tab2, text="Scan tab")
notebook.place(x=32, y=120)
canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 115,
    width = 665,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=346.0,
    y=14.0,
    width=82.0,
    height=30.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=430.0,
    y=14.0,
    width=82.0,
    height=30.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=514.0,
    y=14.0,
    width=82.0,
    height=30.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    332.0,
    57.0,
    image=image_image_1
)
window.resizable(False, False)
window.mainloop()
